/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiUnivoRouteImport } from './routes/api/univo'
import { Route as ApiTxTxRouteImport } from './routes/api/tx.$tx'
import { Route as ApiBlockNumberNumberRouteImport } from './routes/api/block-number.$number'
import { Route as ApiAddressAddressRouteImport } from './routes/api/address.$address'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnivoRoute = ApiUnivoRouteImport.update({
  id: '/api/univo',
  path: '/api/univo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTxTxRoute = ApiTxTxRouteImport.update({
  id: '/api/tx/$tx',
  path: '/api/tx/$tx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlockNumberNumberRoute = ApiBlockNumberNumberRouteImport.update({
  id: '/api/block-number/$number',
  path: '/api/block-number/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddressAddressRoute = ApiAddressAddressRouteImport.update({
  id: '/api/address/$address',
  path: '/api/address/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/api/univo': typeof ApiUnivoRoute
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/api/block-number/$number': typeof ApiBlockNumberNumberRoute
  '/api/tx/$tx': typeof ApiTxTxRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/api/univo': typeof ApiUnivoRoute
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/api/block-number/$number': typeof ApiBlockNumberNumberRoute
  '/api/tx/$tx': typeof ApiTxTxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/api/univo': typeof ApiUnivoRoute
  '/api/address/$address': typeof ApiAddressAddressRoute
  '/api/block-number/$number': typeof ApiBlockNumberNumberRoute
  '/api/tx/$tx': typeof ApiTxTxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/api/univo'
    | '/api/address/$address'
    | '/api/block-number/$number'
    | '/api/tx/$tx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/api/univo'
    | '/api/address/$address'
    | '/api/block-number/$number'
    | '/api/tx/$tx'
  id:
    | '__root__'
    | '/$'
    | '/api/univo'
    | '/api/address/$address'
    | '/api/block-number/$number'
    | '/api/tx/$tx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  ApiUnivoRoute: typeof ApiUnivoRoute
  ApiAddressAddressRoute: typeof ApiAddressAddressRoute
  ApiBlockNumberNumberRoute: typeof ApiBlockNumberNumberRoute
  ApiTxTxRoute: typeof ApiTxTxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/univo': {
      id: '/api/univo'
      path: '/api/univo'
      fullPath: '/api/univo'
      preLoaderRoute: typeof ApiUnivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tx/$tx': {
      id: '/api/tx/$tx'
      path: '/api/tx/$tx'
      fullPath: '/api/tx/$tx'
      preLoaderRoute: typeof ApiTxTxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/block-number/$number': {
      id: '/api/block-number/$number'
      path: '/api/block-number/$number'
      fullPath: '/api/block-number/$number'
      preLoaderRoute: typeof ApiBlockNumberNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/address/$address': {
      id: '/api/address/$address'
      path: '/api/address/$address'
      fullPath: '/api/address/$address'
      preLoaderRoute: typeof ApiAddressAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  ApiUnivoRoute: ApiUnivoRoute,
  ApiAddressAddressRoute: ApiAddressAddressRoute,
  ApiBlockNumberNumberRoute: ApiBlockNumberNumberRoute,
  ApiTxTxRoute: ApiTxTxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
