/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as RscTransactionViewRouteImport } from './routes/rsc/TransactionView'
import { Route as RscAddressHeaderRouteImport } from './routes/rsc/AddressHeader'
import { Route as RscAddressEventsRouteImport } from './routes/rsc/AddressEvents'
import { Route as ApiUnivoRouteImport } from './routes/api/univo'
import { Route as ApiBlockNumberNumberRouteImport } from './routes/api/block-number.$number'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RscTransactionViewRoute = RscTransactionViewRouteImport.update({
  id: '/rsc/TransactionView',
  path: '/rsc/TransactionView',
  getParentRoute: () => rootRouteImport,
} as any)
const RscAddressHeaderRoute = RscAddressHeaderRouteImport.update({
  id: '/rsc/AddressHeader',
  path: '/rsc/AddressHeader',
  getParentRoute: () => rootRouteImport,
} as any)
const RscAddressEventsRoute = RscAddressEventsRouteImport.update({
  id: '/rsc/AddressEvents',
  path: '/rsc/AddressEvents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnivoRoute = ApiUnivoRouteImport.update({
  id: '/api/univo',
  path: '/api/univo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlockNumberNumberRoute = ApiBlockNumberNumberRouteImport.update({
  id: '/api/block-number/$number',
  path: '/api/block-number/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/api/univo': typeof ApiUnivoRoute
  '/rsc/AddressEvents': typeof RscAddressEventsRoute
  '/rsc/AddressHeader': typeof RscAddressHeaderRoute
  '/rsc/TransactionView': typeof RscTransactionViewRoute
  '/api/block-number/$number': typeof ApiBlockNumberNumberRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/api/univo': typeof ApiUnivoRoute
  '/rsc/AddressEvents': typeof RscAddressEventsRoute
  '/rsc/AddressHeader': typeof RscAddressHeaderRoute
  '/rsc/TransactionView': typeof RscTransactionViewRoute
  '/api/block-number/$number': typeof ApiBlockNumberNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/api/univo': typeof ApiUnivoRoute
  '/rsc/AddressEvents': typeof RscAddressEventsRoute
  '/rsc/AddressHeader': typeof RscAddressHeaderRoute
  '/rsc/TransactionView': typeof RscTransactionViewRoute
  '/api/block-number/$number': typeof ApiBlockNumberNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/api/univo'
    | '/rsc/AddressEvents'
    | '/rsc/AddressHeader'
    | '/rsc/TransactionView'
    | '/api/block-number/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/api/univo'
    | '/rsc/AddressEvents'
    | '/rsc/AddressHeader'
    | '/rsc/TransactionView'
    | '/api/block-number/$number'
  id:
    | '__root__'
    | '/$'
    | '/api/univo'
    | '/rsc/AddressEvents'
    | '/rsc/AddressHeader'
    | '/rsc/TransactionView'
    | '/api/block-number/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  ApiUnivoRoute: typeof ApiUnivoRoute
  RscAddressEventsRoute: typeof RscAddressEventsRoute
  RscAddressHeaderRoute: typeof RscAddressHeaderRoute
  RscTransactionViewRoute: typeof RscTransactionViewRoute
  ApiBlockNumberNumberRoute: typeof ApiBlockNumberNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsc/TransactionView': {
      id: '/rsc/TransactionView'
      path: '/rsc/TransactionView'
      fullPath: '/rsc/TransactionView'
      preLoaderRoute: typeof RscTransactionViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsc/AddressHeader': {
      id: '/rsc/AddressHeader'
      path: '/rsc/AddressHeader'
      fullPath: '/rsc/AddressHeader'
      preLoaderRoute: typeof RscAddressHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsc/AddressEvents': {
      id: '/rsc/AddressEvents'
      path: '/rsc/AddressEvents'
      fullPath: '/rsc/AddressEvents'
      preLoaderRoute: typeof RscAddressEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/univo': {
      id: '/api/univo'
      path: '/api/univo'
      fullPath: '/api/univo'
      preLoaderRoute: typeof ApiUnivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/block-number/$number': {
      id: '/api/block-number/$number'
      path: '/api/block-number/$number'
      fullPath: '/api/block-number/$number'
      preLoaderRoute: typeof ApiBlockNumberNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  ApiUnivoRoute: ApiUnivoRoute,
  RscAddressEventsRoute: RscAddressEventsRoute,
  RscAddressHeaderRoute: RscAddressHeaderRoute,
  RscTransactionViewRoute: RscTransactionViewRoute,
  ApiBlockNumberNumberRoute: ApiBlockNumberNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
